version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - web
    volumes:
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis
    networks:
      - web
    ports:
      - 6379:6379

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - web

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    networks:
      - web
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  app:
    build: .
    environment:
      DB_HOST: db 
      DB_PORT: 5432
      DB_NAME: tasks
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      NEO4J_HOST: neo4j
      NEO4J_PORT: 7687
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - 5002:5000
    networks:
      - web
    depends_on:
      - db
      - mongo
      - neo4j
      - kafka
    volumes:
      - .:/opt/app
    command: poetry run python3 -m flask --app app.py --debug run --host=0.0.0.0

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

  neo4j:
    image: neo4j:4.4
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - web
    environment:
      NEO4J_AUTH: neo4j/password

networks:
  web:
    driver: bridge
