name: Docker Image CI/CD

on:
  push:
    branches: ['devSam']
  
  pull_request:
    branches: ['devSam']

jobs:
 
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run pytest
      run: pytest
      
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: docker build -t samvalverde/SurveySystem:latest .
      
    - name: Tag Docker image for GitHub Container Registry
      run: docker tag samvalverde/SurveySystem:latest ghcr.io/${{ github.repository_owner }}/SurveySystem:latest
      
    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/SurveySystem:latest
      
    - name: Clean up Docker images
      run: docker image prune -f
          
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ needs.build-and-push.result == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Change to directory containing docker-compose.yml
      run: cd ./python-flask-restapi/

    - name: Run docker-compose up
      run: docker-compose up -d
