name: CI/CD

on:
  push:
    branches: [ 'devSam' ]
  pull_request:
    branches: [ 'devSam' ]

jobs:
  # test:
    # runs-on: ubuntu-latest
    
    # steps:
    # - name: Checkout code
      #uses: actions/checkout@v2
      
    #- name: Set up Python
      #uses: actions/setup-python@v2
      #with:
        #python-version: 3.6  # Adjust to your Python version
    
    #- name: Install dependencies
      #run: |
        #pip install poetry
        #poetry install
        
    #- name: Run pytest
      #run: poetry run pytest

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./python-flask-restapi/Dockerfile
        push: true
        tags: ${{ github.repository }}:latest
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
        
  deploy:
    runs-on: ubuntu-latest
    #needs: test
    #if: ${{ needs.test.result == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run docker-compose up
      run: docker-compose up -d