name: Docker Image CI/CD

on:
  push:
    branches:
      - main
      - devSam
      - devCrisac
  
  pull_request:
    branches:
      - main
      - devSam
      - devCrisac

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2' # Versión de Python a utilizar
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - name: Run pytest
        run: pytest

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: docker build -t samvalverde/surveysystem:latest ./python-flask-restapi/
      
      - name: Tag Docker image for GitHub Container Registry
        run: docker tag samvalverde/surveysystem:latest ghcr.io/${{ github.repository_owner }}/surveysystem:latest
      
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/surveysystem:latest
      
      - name: Clean up Docker images
        run: docker image prune -f

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ needs.build-and-push.result == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Change to directory containing docker-compose.yml
        run: cd ./python-flask-restapi/
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull Docker image from GitHub Container Registry
        run: docker pull ghcr.io/${{ github.repository_owner }}/surveysystem:latest
      
      - name: Run docker-compose up
        run: docker-compose up -d
