name: pytest

on:
  push:
    branches:
      - Emma
  pull_request:
    branches:
      - Emma

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.2'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run pytest
      run: pytest
